### ISSUE TITLE
好巧哦

### ISSUE THREAD

**Issue by WangGuibin** [alitan2014/VideoEditDemo#1]
hello ~
老谭

**Comment by WangGuibin** [comment]
你写的这个只有录制 ，没有编辑啊 标题党了

**Comment by alitan2014** [comment]
没有搞完------------------ 原始邮件 ------------------
发件人: "CoderWGB"<notifications@github.com>
发送时间: 2019年8月26日(星期一) 晚上9:27
收件人: "alitan2014/VideoEditDemo"<VideoEditDemo@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [alitan2014/VideoEditDemo] 好巧哦 (#1)



你写的这个只有录制 ，没有编辑啊 标题党了
 
&mdash;

**Comment by WangGuibin** [comment]
> 没有搞完------------------ 原始邮件 ------------------ 发件人: "CoderWGB"<notifications@github.com> 发送时间: 2019年8月26日(星期一) 晚上9:27 收件人: "alitan2014/VideoEditDemo"<VideoEditDemo@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: Re: [alitan2014/VideoEditDemo] 好巧哦 (#1) 你写的这个只有录制 ，没有编辑啊 标题党了 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

好的好的 加油
